name: Users CI

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 5
            - name: Use node version ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Remove existing TypeScript
              run: |
                  npm uninstall typescript --no-save
                  npm uninstall tslint --no-save
            - name: install user dependencies
              run: |
                  npm install "microservices/user" --production=false
                  cd "microservices/user" &&  npm install @typescript-eslint/eslint-plugin@latest --save-dev && npx eslint "./**.ts"
            - name: User tests
              run: |
                npm install "microservices/user" --production=false
                cd "microservices/user/src/core/data-access" && npm test
            - name: install fridge dependencies
              run: |
                  npm install "microservices/fridge" --production=false
                  cd "microservices/fridge" &&  npm install @typescript-eslint/eslint-plugin@latest --save-dev && npx eslint "./**.ts"
            - name: Fridge tests
              run: |
                npm install "microservices/fridge" --production=false
                cd "microservices/fridge/src/core/data-access" && npm test
            - name: install post dependencies
              run: |
                  npm install "microservices/post" --production=false
                  cd "microservices/post" &&  npm install @typescript-eslint/eslint-plugin@latest --save-dev && npx eslint "./**.ts"
            - name: Post tests
              run: |
                npm install "microservices/post" --production=false
                cd "microservices/post/src/core/data-access" && npm test